// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GamesWebApi.Models
{
    public partial class TbPlatform
    {
        public TbPlatform()
        {
            TbGames = new HashSet<TbGames>();
        }

        public int Idplatform { get; set; }
        public string Platform { get; set; }
        public string Deskripsi { get; set; }
        public byte? Status { get; set; }

        public virtual ICollection<TbGames> TbGames { get; set; }
    }
}